Add missing not optional arguments in `Tile.createEmpty` call
This is the fix for following error that is currently present in logs
of production pod:
```
Error: z, x, y should b integer. iwnput: z = undefined, x = undefined, y = undefined
    at new Tile (file:///usr/src/app/src/tile.mjs:72:13)
    at Tile.createEmpty (file:///usr/src/app/src/tile.mjs:62:12)
    at constructParentTileFromChildren (file:///usr/src/app/src/tile.mjs:118:17)
    at source (file:///usr/src/app/src/mosaic.mjs:60:24)
    at async Promise.all (index 3)
    at async source (file:///usr/src/app/src/mosaic.mjs:53:19)
    at async Promise.all (index 1)
    at async source (file:///usr/src/app/src/mosaic.mjs:53:19)
    at async Promise.all (index 1)
    at async source (file:///usr/src/app/src/mosaic.mjs:53:19)
```